version: '3.7'

services:
  web:
    depends_on:
      - sonic
    image: rs-translations
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - sqlite:/data/
    ports:
      - "6000:80"
    networks:
      - rstranslations
  sonic:
    image: valeriansaliou/sonic:v1.3.2
    restart: unless-stopped
    volumes:
      - .docker/sonic.cfg:/etc/sonic.cfg
      - sonic:/var/lib/sonic/store/
    ports:
      - "1491:1491"
    networks:
      - rstranslations
networks:
  rstranslations:
volumes:
  sqlite:
  sonic: