version: '3.3'

services:
    web:
        depends_on:
            - mongo
            - sonic
        image: rstranslations
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        ports:
            - "6001:3000"
        networks:
            - rstranslations
    mongo:
        image: mongo:4
        restart: unless-stopped
        command: mongod
        volumes:
            - ./docker/mongo/:/docker-entrypoint-initdb.d/
            - mongo:/data/db
        ports:
            - "6002:27017"
        networks:
            - rstranslations
        environment:
            - MONGO_INITDB_DATABASE=rstranslations
            - MONGO_INITDB_ROOT_USERNAME=rstranslations
            - MONGO_INITDB_ROOT_PASSWORD=rstranslations
    sonic:
        image: valeriansaliou/sonic:v1.2.3
        restart: unless-stopped
        ports:
            - '6003:1491'
        volumes:
            - ./sonic-config.cfg:/etc/sonic.cfg
            - sonic:/var/lib/sonic/store/
networks:
    rstranslations:
volumes:
    mongo:
    sonic: