version: '3.7'

services:
    web:
        depends_on:
            - elastic
        image: rs-translations
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        ports:
            - 6000:80
        networks:
            - rstranslations
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        restart: unless-stopped
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - rstranslations
    kibana:
        depends_on:
            - elastic
        image: docker.elastic.co/kibana/kibana:7.9.1
        restart: "no"
        environment:
            ELASTICSEARCH_HOSTS: http://elastic:9200
        ports:
            - 5601:5601
        networks:
            - rstranslations
networks:
    rstranslations:
volumes:
    elastic: