version: '3.3'

services:
    web:
        depends_on:
            - mongo
        image: rs-translations
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        ports:
            - "6001:3000"
        networks:
            - rstranslations
    mongo:
        image: mongo:4
        restart: unless-stopped
        command: mongod
        volumes:
            - ./docker/mongo/:/docker-entrypoint-initdb.d/
            - mongo:/data/db
        ports:
            - "6002:27017"
        networks:
            - rstranslations
        environment:
            - MONGO_INITDB_DATABASE=rstranslations
            - MONGO_INITDB_ROOT_USERNAME=rstranslations
            - MONGO_INITDB_ROOT_PASSWORD=rstranslations
networks:
    rstranslations:
volumes:
    mongo:
    sonic: